[version]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/OPNsense/SpeedtestSurfHost/speedtest.py version
parameters:
type:script_output
message:Show the speedtest program in use

[serverlist]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/OPNsense/SpeedtestSurfHost/speedtest.py list
parameters:
type:script_output
message:List the nearest speedtest servers

[run]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/OPNsense/SpeedtestSurfHost/speedtest.py run
parameters:%s
type:script_output
message:Run a speedtest
description:Run speedtest (SurfHost)

[stat]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/OPNsense/SpeedtestSurfHost/speedtest.py stat
parameters:
type:script_output
message:Show speedtest statistics

[log]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/OPNsense/SpeedtestSurfHost/speedtest.py log
parameters:
type:script_output
message:Show the latest speedtest results

[recent]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/OPNsense/SpeedtestSurfHost/speedtest.py recent
parameters:
type:script_output
message:Show the most recent speedtest result

[deletelog]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/OPNsense/SpeedtestSurfHost/speedtest.py clear
parameters:
type:script_output
message:Clear the speedtest history

[sync]
command:/bin/sh /usr/local/opnsense/scripts/OPNsense/SpeedtestSurfHost/install_backend.sh sync
parameters:
type:script_output
message:Install the speedtest program chosen in the settings
